### ISSUE TITLE
RSA key generated less than 4096-bit

### ISSUE THREAD

**Issue by B-Interactive** [bsdlabs/ssh-hardening#14]
The [SSH Hardening Guides](https://www.sshaudit.com/hardening_guides.html) leverage 4096-bit RSA keys as standard.  [The command](https://github.com/bsdlabs/ssh-hardening/blob/main/README.md?plain=1#L26) `service sshd keygen` produces a 3072-bit RSA key.

I acknowledge the _practical_ security of the two (3072, 4096) still puts _both_ of them in the realm of unbreakable.

**Comment by jlduran** [comment]
Is this related to #6?
At any rate, we have the latest OpenSSH version now, the defaults should be more than fine, with a few arguable exceptions.

**Comment by B-Interactive** [comment]
Yes it would relate to #6 (just spotted that branch too).  The minimum has since increased from 2048 to 3072 bits, but I believe the standard the SSH Hardening Guides have established, is 4096-bits.  The merits of 3072 vs 4096 are perhaps a topic of heavy debate and discussion and likely beyond the scope of my knowledge.

My appeal is more towards aligning with the baseline established by the SSH Hardening Guides, if that's something to be considered.
