### ISSUE TITLE
Server: diffie-hellman-group14-sha256

### ISSUE THREAD

**Issue by B-Interactive** [bsdlabs/ssh-hardening#24]
For server config, just noting, that the key exchange algorithm `diffie-hellman-group14-sha256` is listed as being present in the "Comparative table: Default vs. Hardened" under [Hardened config](https://github.com/bsdlabs/ssh-hardening/blob/5db1e0dcda23de5e129c2cd0fa14384ec9412c02/server.md?plain=1#L256), but it hasn't been included as a key exchange algorithm in [the supplied command](https://github.com/bsdlabs/ssh-hardening/blob/5db1e0dcda23de5e129c2cd0fa14384ec9412c02/server.md?plain=1#L37).

**Comment by jlduran** [comment]
Thank you!
It shouldn't be on the hardened side of the table indeed:
```
# algorithm recommendations (for OpenSSH 9.3)
(rec) -diffie-hellman-group14-sha256        -- kex algorithm to remove
```
