### ISSUE TITLE
Send FreeBSD server and client SSH hardening guides upstream

### ISSUE THREAD

**Issue by koobs** [bsdlabs/ssh-hardening#3]
We'd like FreeBSD SSH Server & Client Hardening Guides upstream and listed on sshaudit.com, ideally in the Official list (find out how).

Submission Instructions: https://github.com/jtesta/ssh-audit/wiki/SSH-Hardening-Guides-Index

Depends-On #2

**Comment by jlduran** [comment]
Let's wait a few hours/days until the latest version of the package has been published for 12.4, so we submit the guide upstream with a green checkmark.

**Comment by koobs** [comment]
You rock @jlduran :D

**Comment by jlduran** [comment]
I would say @emaste deserves most of the credit. For the first time (I guess) the FreeBSD project had a release with a newer version of OpenSSH than OpenBSD (if only for a few days)!

**Comment by jlduran** [comment]
Done!
https://github.com/jtesta/ssh-audit/issues/189

**Comment by jlduran** [comment]
https://www.sshaudit.com/hardening_guides.html

**Comment by koobs** [comment]
Thanks @jtesta!
